/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AC_INICIO;


import AC_CONNECTBD.ConexaoAC;
import AC_DAO.AC_DAOUSUARIO;
import AC_MODEL.AC_MDUSUARIO;
import java.sql.Connection;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import sun.security.util.Password;

/**
 *
 * @author LucasxTakeshi
 */
public class AC_CADGERENTE extends javax.swing.JFrame {

    /**
     * Creates new form AC_CADGERENTE
     */
    public AC_CADGERENTE() {
        initComponents();
        FormatCamp();
        setTitle("Cadastra um novo gerente - AutoCar");
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(400, 530);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painel_fundo = new javax.swing.JPanel();
        painel_txt = new javax.swing.JPanel();
        lbl_cadgerente = new javax.swing.JLabel();
        lbl_fone = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        txt_end = new javax.swing.JTextField();
        lbl_cpf = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_rg = new javax.swing.JLabel();
        lbl_end = new javax.swing.JLabel();
        lbl_login = new javax.swing.JLabel();
        txt_login = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_sair = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();
        txt_rg = new javax.swing.JFormattedTextField();
        txt_cpf = new javax.swing.JFormattedTextField();
        txt_fone = new javax.swing.JFormattedTextField();
        lbl_senha = new javax.swing.JLabel();
        txt_senha = new javax.swing.JPasswordField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel_fundo.setBackground(new java.awt.Color(255, 255, 255));
        painel_fundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        painel_fundo.setLayout(null);

        painel_txt.setBackground(new java.awt.Color(70, 113, 197));
        painel_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        painel_txt.setForeground(new java.awt.Color(255, 255, 255));
        painel_txt.setLayout(null);

        lbl_cadgerente.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_cadgerente.setForeground(new java.awt.Color(0, 0, 0));
        lbl_cadgerente.setText("CADASTRO GERENTE");
        painel_txt.add(lbl_cadgerente);
        lbl_cadgerente.setBounds(70, 10, 260, 50);

        painel_fundo.add(painel_txt);
        painel_txt.setBounds(0, 0, 400, 70);

        lbl_fone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_fone.setForeground(new java.awt.Color(0, 0, 0));
        lbl_fone.setText("Fone  :");
        painel_fundo.add(lbl_fone);
        lbl_fone.setBounds(190, 190, 50, 30);

        lbl_nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_nome.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nome.setText("Nome :");
        painel_fundo.add(lbl_nome);
        lbl_nome.setBounds(20, 110, 50, 30);

        txt_nome.setBackground(new java.awt.Color(255, 255, 255));
        txt_nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_nome.setForeground(new java.awt.Color(0, 0, 0));
        txt_nome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        painel_fundo.add(txt_nome);
        txt_nome.setBounds(80, 110, 300, 30);

        lbl_email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(0, 0, 0));
        lbl_email.setText("E-mail :");
        painel_fundo.add(lbl_email);
        lbl_email.setBounds(20, 150, 60, 30);

        txt_end.setBackground(new java.awt.Color(255, 255, 255));
        txt_end.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_end.setForeground(new java.awt.Color(0, 0, 0));
        txt_end.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_endActionPerformed(evt);
            }
        });
        painel_fundo.add(txt_end);
        txt_end.setBounds(110, 270, 270, 30);

        lbl_cpf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_cpf.setForeground(new java.awt.Color(0, 0, 0));
        lbl_cpf.setText("CPF :");
        painel_fundo.add(lbl_cpf);
        lbl_cpf.setBounds(20, 190, 60, 30);

        txt_email.setBackground(new java.awt.Color(255, 255, 255));
        txt_email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(0, 0, 0));
        txt_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        painel_fundo.add(txt_email);
        txt_email.setBounds(80, 150, 300, 30);

        lbl_rg.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_rg.setForeground(new java.awt.Color(0, 0, 0));
        lbl_rg.setText("RG :");
        painel_fundo.add(lbl_rg);
        lbl_rg.setBounds(20, 230, 60, 30);

        lbl_end.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_end.setForeground(new java.awt.Color(0, 0, 0));
        lbl_end.setText("Endereço :");
        painel_fundo.add(lbl_end);
        lbl_end.setBounds(20, 270, 90, 30);

        lbl_login.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_login.setForeground(new java.awt.Color(0, 0, 0));
        lbl_login.setText("Login :");
        painel_fundo.add(lbl_login);
        lbl_login.setBounds(20, 310, 60, 30);

        txt_login.setBackground(new java.awt.Color(255, 255, 255));
        txt_login.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_login.setForeground(new java.awt.Color(0, 0, 0));
        txt_login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        painel_fundo.add(txt_login);
        txt_login.setBounds(80, 310, 300, 30);

        jLabel1.setText("Desenvolvido por JJEL");
        painel_fundo.add(jLabel1);
        jLabel1.setBounds(140, 480, 130, 16);

        btn_sair.setBackground(new java.awt.Color(255, 51, 51));
        btn_sair.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_sair.setForeground(new java.awt.Color(0, 0, 0));
        btn_sair.setText("SAIR");
        btn_sair.setBorder(new javax.swing.border.MatteBorder(null));
        btn_sair.setOpaque(false);
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });
        painel_fundo.add(btn_sair);
        btn_sair.setBounds(220, 410, 130, 50);

        btn_cadastrar.setBackground(new java.awt.Color(51, 255, 51));
        btn_cadastrar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btn_cadastrar.setForeground(new java.awt.Color(0, 0, 0));
        btn_cadastrar.setText("CADASTRAR");
        btn_cadastrar.setBorder(new javax.swing.border.MatteBorder(null));
        btn_cadastrar.setOpaque(false);
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        painel_fundo.add(btn_cadastrar);
        btn_cadastrar.setBounds(50, 410, 130, 50);

        txt_rg.setBackground(new java.awt.Color(255, 255, 255));
        txt_rg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_rg.setForeground(new java.awt.Color(0, 0, 0));
        painel_fundo.add(txt_rg);
        txt_rg.setBounds(80, 230, 300, 30);

        txt_cpf.setBackground(new java.awt.Color(255, 255, 255));
        txt_cpf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_cpf.setForeground(new java.awt.Color(0, 0, 0));
        painel_fundo.add(txt_cpf);
        txt_cpf.setBounds(80, 190, 100, 30);

        txt_fone.setBackground(new java.awt.Color(255, 255, 255));
        txt_fone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_fone.setForeground(new java.awt.Color(0, 0, 0));
        painel_fundo.add(txt_fone);
        txt_fone.setBounds(250, 190, 130, 30);

        lbl_senha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_senha.setForeground(new java.awt.Color(0, 0, 0));
        lbl_senha.setText("Senha :");
        painel_fundo.add(lbl_senha);
        lbl_senha.setBounds(20, 350, 60, 30);

        txt_senha.setBackground(new java.awt.Color(255, 255, 255));
        txt_senha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_senha.setForeground(new java.awt.Color(0, 0, 0));
        txt_senha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        painel_fundo.add(txt_senha);
        txt_senha.setBounds(80, 350, 300, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FormatCamp(){
        
        try {
            
            MaskFormatter cpf = new MaskFormatter("###.###.###-##");
            cpf.install(txt_cpf);
            
            MaskFormatter fone = new MaskFormatter("(##)#####-####");
            fone.install(txt_fone);
            
            MaskFormatter rg = new MaskFormatter("##.###.###");
            rg.install(txt_rg);
            
        } catch (ParseException ex) {
        
            JOptionPane.showMessageDialog(null, "Erro na formatação do campo", "Erro", JOptionPane.ERROR_MESSAGE);
        
        }
        
    }
    
    private void txt_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_endActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_endActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        
        if (txt_nome.equals("") || txt_email.equals("") || txt_cpf.equals("") || txt_fone.equals("") || txt_rg.equals("") || txt_end.equals("") || txt_login.equals("") || txt_senha.equals("")){
         
            JOptionPane.showMessageDialog(null, "Preeencha todos os campos", 
                   "Concessionária AutoCar", JOptionPane.ERROR_MESSAGE);
       
       }else{
        
        Connection con = ConexaoAC.OpenConect();
        AC_MDUSUARIO c = new AC_MDUSUARIO();
        AC_DAOUSUARIO dao = new AC_DAOUSUARIO();
        
        c.setNome(txt_nome.getText());
        c.setEmail(txt_email.getText());
        c.setCPF(txt_cpf.getText());
        c.setTelefone(txt_fone.getText());
        c.setRG(txt_rg.getText());
        c.setEndereco(txt_end.getText());
        c.setLogin(txt_login.getText());
        c.setSenha(txt_senha.getText());
        
        dao.save(c);

        new AC_ENTRADA().setVisible(true);
        dispose();
        
        }
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AC_CADGERENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AC_CADGERENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AC_CADGERENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AC_CADGERENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AC_CADGERENTE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cadgerente;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_end;
    private javax.swing.JLabel lbl_fone;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_rg;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JPanel painel_fundo;
    private javax.swing.JPanel painel_txt;
    private javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_end;
    private javax.swing.JFormattedTextField txt_fone;
    private javax.swing.JTextField txt_login;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JFormattedTextField txt_rg;
    private javax.swing.JPasswordField txt_senha;
    // End of variables declaration//GEN-END:variables
}
