package AC_INICIO;

/**
 *
 * @author LucasxTakeshi
 */
public class AC_ENTRADA extends javax.swing.JFrame {

    /**
     * Creates new form AC_ENTRADA
     */
    public AC_ENTRADA() {
        initComponents();
        setTitle("Concessionária AutoCar");
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(400, 530);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_fundo = new javax.swing.JPanel();
        label_ac = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label_bv = new javax.swing.JLabel();
        btn_sair = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();
        btn_logar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel_fundo.setBackground(new java.awt.Color(70, 113, 197));
        painel_fundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        painel_fundo.setLayout(null);

        label_ac.setFont(new java.awt.Font("Magneto", 1, 48)); // NOI18N
        label_ac.setForeground(new java.awt.Color(0, 0, 0));
        label_ac.setText(" AutoCar");
        painel_fundo.add(label_ac);
        label_ac.setBounds(60, 40, 260, 60);
        painel_fundo.add(jSeparator1);
        jSeparator1.setBounds(110, 100, 170, 10);

        label_bv.setBackground(new java.awt.Color(255, 255, 255));
        label_bv.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        label_bv.setForeground(new java.awt.Color(0, 0, 0));
        label_bv.setText("Bem Vindo");
        painel_fundo.add(label_bv);
        label_bv.setBounds(140, 130, 120, 29);

        btn_sair.setBackground(new java.awt.Color(255, 255, 255));
        btn_sair.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        btn_sair.setForeground(new java.awt.Color(0, 0, 0));
        btn_sair.setText("SAIR");
        btn_sair.setBorder(new javax.swing.border.MatteBorder(null));
        btn_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_sair.setOpaque(false);
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });
        painel_fundo.add(btn_sair);
        btn_sair.setBounds(60, 360, 280, 50);

        btn_cadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cadastrar.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        btn_cadastrar.setForeground(new java.awt.Color(0, 0, 0));
        btn_cadastrar.setText("CADASTRAR");
        btn_cadastrar.setBorder(new javax.swing.border.MatteBorder(null));
        btn_cadastrar.setOpaque(false);
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        painel_fundo.add(btn_cadastrar);
        btn_cadastrar.setBounds(60, 200, 280, 50);

        btn_logar.setBackground(new java.awt.Color(255, 255, 255));
        btn_logar.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        btn_logar.setForeground(new java.awt.Color(0, 0, 0));
        btn_logar.setText("LOGAR");
        btn_logar.setBorder(new javax.swing.border.MatteBorder(null));
        btn_logar.setOpaque(false);
        btn_logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logarActionPerformed(evt);
            }
        });
        painel_fundo.add(btn_logar);
        btn_logar.setBounds(60, 280, 280, 50);

        jLabel1.setText("Desenvolvido por JJEL");
        painel_fundo.add(jLabel1);
        jLabel1.setBounds(140, 470, 130, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        new AC_CADGERENTE().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_logarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logarActionPerformed
        new AC_LOGIN().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_logarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AC_ENTRADA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AC_ENTRADA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AC_ENTRADA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AC_ENTRADA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AC_ENTRADA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_logar;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_ac;
    private javax.swing.JLabel label_bv;
    private javax.swing.JPanel painel_fundo;
    // End of variables declaration//GEN-END:variables
}
