/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AC_INICIO;

import AC_CONNECTBD.ConexaoAC;
import AC_DAO.AC_DAOCLIENTE;
import AC_MODEL.AC_MDCLIENTE;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Graphics;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LucasxTakeshi
 */
public class AC_PFUNCIONARIO extends javax.swing.JFrame {

    /**
     * Creates new form AC_PGERENTE
     */
    public AC_PFUNCIONARIO() {
        initComponents();
        setTitle("Acesso exclusivo funcionário - AutoCar");
        Table();
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(640, 450);
    }

    
    
    public void Table(){
        
        DefaultTableModel model = (DefaultTableModel) jTClientes.getModel();
        model.setNumRows(0);
        AC_DAOCLIENTE cdao  = new AC_DAOCLIENTE();
        
        for (AC_MDCLIENTE c: cdao.Mostrar()){
            
            model.addRow(new Object[]{
            
                c.getIdcliente(),
                c.getNome(),
                c.getEmail(),
                c.getCpf(),
                c.getTelefone(),
                c.getRg(),
                c.getCidade(),
                c.getEstado(),
                c.getCnh()
                
            });
            
        }
        
    }
    
    public void BuscarCliente(String nome){
        
        DefaultTableModel model = (DefaultTableModel) jTClientes.getModel();
        model.setNumRows(0);
        AC_DAOCLIENTE cdao  = new AC_DAOCLIENTE();
        
        for (AC_MDCLIENTE c: cdao.BuscarCliente(nome)){
            
            model.addRow(new Object[]{
           
                c.getIdcliente(),
                c.getNome(),
                c.getEmail(),
                c.getCpf(),
                c.getTelefone(),
                c.getRg(),
                c.getCidade(),
                c.getEstado(),
                c.getCnh()
                
            });
            
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_fundo = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_txt1 = new javax.swing.JLabel();
        btn_atualizar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTClientes = new javax.swing.JTable();
        txt_busca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cnh = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        alt_nome = new javax.swing.JTextField();
        alt_email = new javax.swing.JTextField();
        alt_cpf = new javax.swing.JTextField();
        alt_rg = new javax.swing.JTextField();
        alt_fone = new javax.swing.JTextField();
        alt_estado = new javax.swing.JTextField();
        alt_cidade = new javax.swing.JTextField();
        alt_cnh = new javax.swing.JTextField();
        label_ac = new javax.swing.JLabel();
        barra_menug = new javax.swing.JMenuBar();
        menu_funcionario = new javax.swing.JMenu();
        item_cadastrarcliente = new javax.swing.JMenuItem();
        item_alterarcliente = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        item_sair = new javax.swing.JMenuItem();
        item_buscarcliente = new javax.swing.JMenu();
        item_buscarveiculo = new javax.swing.JMenuItem();
        menu_status = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel_fundo.setBackground(new java.awt.Color(255, 255, 255));
        painel_fundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        painel_fundo.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        lbl_txt1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_txt1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_txt1.setText("Todos os nossos clientes");
        jPanel1.add(lbl_txt1);
        lbl_txt1.setBounds(256, 9, 170, 17);

        btn_atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/arrow_refresh.png"))); // NOI18N
        btn_atualizar.setText("ATUALIZAR");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_atualizar);
        btn_atualizar.setBounds(510, 7, 114, 20);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(0, 34, 630, 10);

        jTClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "E-MAIL", "CPF", "FONE", "RG", "CIDADE", "ESTADO", "CNH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClientesMouseClicked(evt);
            }
        });
        jTClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTClientesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTClientes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 630, 140);
        jPanel1.add(txt_busca);
        txt_busca.setBounds(6, 6, 100, 22);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/zoom.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(112, 6, 46, 22);

        jLabel1.setText("Nome :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(34, 212, 50, 16);

        jLabel2.setText("E-mail :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 210, 50, 16);

        jLabel3.setText("CPF :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 210, 40, 16);

        jLabel4.setText("Fone :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 212, 50, 16);

        jLabel5.setText("RG :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 250, 50, 16);

        jLabel6.setText("Cidade :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 250, 50, 16);

        jLabel7.setText("Estado :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(320, 250, 50, 16);

        cnh.setText("CNH :");
        jPanel1.add(cnh);
        cnh.setBounds(460, 250, 50, 16);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/page_edit.png"))); // NOI18N
        jButton2.setText("Alterar dados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(34, 292, 130, 32);
        jPanel1.add(alt_nome);
        alt_nome.setBounds(80, 210, 79, 24);
        jPanel1.add(alt_email);
        alt_email.setBounds(220, 210, 110, 24);
        jPanel1.add(alt_cpf);
        alt_cpf.setBounds(375, 208, 79, 24);
        jPanel1.add(alt_rg);
        alt_rg.setBounds(60, 250, 79, 24);
        jPanel1.add(alt_fone);
        alt_fone.setBounds(500, 210, 90, 24);
        jPanel1.add(alt_estado);
        alt_estado.setBounds(370, 250, 80, 24);
        jPanel1.add(alt_cidade);
        alt_cidade.setBounds(200, 250, 110, 24);
        jPanel1.add(alt_cnh);
        alt_cnh.setBounds(500, 250, 90, 24);

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(0, 50, 630, 370);

        label_ac.setFont(new java.awt.Font("Magneto", 1, 48)); // NOI18N
        label_ac.setForeground(new java.awt.Color(0, 0, 0));
        label_ac.setText(" AutoCar");
        jDesktopPane1.add(label_ac);
        label_ac.setBounds(180, 0, 260, 40);

        javax.swing.GroupLayout painel_fundoLayout = new javax.swing.GroupLayout(painel_fundo);
        painel_fundo.setLayout(painel_fundoLayout);
        painel_fundoLayout.setHorizontalGroup(
            painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        painel_fundoLayout.setVerticalGroup(
            painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );

        barra_menug.setBackground(new java.awt.Color(153, 153, 153));
        barra_menug.setForeground(new java.awt.Color(0, 0, 0));

        menu_funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/user_suit.png"))); // NOI18N
        menu_funcionario.setText("Funcionário");

        item_cadastrarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/user_green.png"))); // NOI18N
        item_cadastrarcliente.setText("Cadastrar cliente");
        item_cadastrarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_cadastrarclienteActionPerformed(evt);
            }
        });
        menu_funcionario.add(item_cadastrarcliente);

        item_alterarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/page_edit.png"))); // NOI18N
        item_alterarcliente.setText("Alterar dados");
        item_alterarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_alterarclienteActionPerformed(evt);
            }
        });
        menu_funcionario.add(item_alterarcliente);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cart_put.png"))); // NOI18N
        jMenuItem1.setText("Fechar venda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_funcionario.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/coins.png"))); // NOI18N
        jMenuItem2.setText("Promoções");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu_funcionario.add(jMenuItem2);

        item_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/door_out.png"))); // NOI18N
        item_sair.setText("Sair");
        item_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_sairActionPerformed(evt);
            }
        });
        menu_funcionario.add(item_sair);

        barra_menug.add(menu_funcionario);

        item_buscarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/zoom.png"))); // NOI18N
        item_buscarcliente.setText("Pesquisar");

        item_buscarveiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/car_add.png"))); // NOI18N
        item_buscarveiculo.setText("Buscar veículos");
        item_buscarveiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_buscarveiculoActionPerformed(evt);
            }
        });
        item_buscarcliente.add(item_buscarveiculo);

        barra_menug.add(item_buscarcliente);

        menu_status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bullet_green.png"))); // NOI18N
        menu_status.setText("Status");
        menu_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_statusActionPerformed(evt);
            }
        });
        barra_menug.add(menu_status);

        setJMenuBar(barra_menug);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_sairActionPerformed
        new AC_ENTRADA().setVisible(true);
        dispose();
    }//GEN-LAST:event_item_sairActionPerformed

    private void menu_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_statusActionPerformed
        
        
    }//GEN-LAST:event_menu_statusActionPerformed

    private void item_cadastrarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_cadastrarclienteActionPerformed
        
        CadastrarCliente CadCliente = new CadastrarCliente();
        jDesktopPane1.add(CadCliente);
        CadCliente.setVisible(true);
        
    }//GEN-LAST:event_item_cadastrarclienteActionPerformed

    private void jTClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClientesMouseClicked

        if(jTClientes.getSelectedRow() != 1){

            alt_nome.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 1).toString());
            alt_email.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 2).toString());
            alt_cpf.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 3).toString());
            alt_fone.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 4).toString());
            alt_rg.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 5).toString());
            alt_cidade.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 6).toString());
            alt_estado.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 7).toString());
            alt_cnh.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 8).toString());

        }

    }//GEN-LAST:event_jTClientesMouseClicked

    private void jTClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTClientesKeyReleased

        if(jTClientes.getSelectedRow() != 1){

            alt_nome.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 1).toString());
            alt_email.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 2).toString());
            alt_cpf.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 3).toString());
            alt_fone.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 4).toString());
            alt_rg.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 5).toString());
            alt_cidade.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 6).toString());
            alt_estado.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 7).toString());
            alt_cnh.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 8).toString());

        }

    }//GEN-LAST:event_jTClientesKeyReleased

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        Table();
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        BuscarCliente(txt_busca.getText());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(jTClientes.getSelectedRow() != 1){
         
        Connection con = ConexaoAC.OpenConect();
        AC_MDCLIENTE c = new AC_MDCLIENTE();
        AC_DAOCLIENTE dao = new AC_DAOCLIENTE();
        AC_PFUNCIONARIO table = new AC_PFUNCIONARIO();

        c.setNome(alt_nome.getText());
        c.setEmail(alt_email.getText());
        c.setCpf(alt_cpf.getText());
        c.setTelefone(alt_fone.getText());
        c.setRg(alt_rg.getText());
        c.setCidade(alt_cidade.getText());
        c.setEstado(alt_estado.getText());
        c.setCnh(alt_cnh.getText());
        c.setIdcliente((int)jTClientes.getValueAt(jTClientes.getSelectedRow(), 0));
        
        dao.AlterarCliente(c);
        
        alt_nome.setText("");
        alt_email.setText("");
        alt_cpf.setText("");
        alt_fone.setText("");
        alt_rg.setText("");
        alt_cidade.setText("");
        alt_estado.setText("");
        alt_cnh.setText("");
        
        
        Table();
        
        }else{
            
            JOptionPane.showMessageDialog(null, "Selecione uma veículo para fazer a alteração");
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void item_alterarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_alterarclienteActionPerformed
       
        JOptionPane.showMessageDialog(null, "Selecione um cliente na tabela.");
        
    }//GEN-LAST:event_item_alterarclienteActionPerformed

    private void item_buscarveiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_buscarveiculoActionPerformed
        
        BuscarVeiculos BuscarCar = new BuscarVeiculos();
        jDesktopPane1.add(BuscarCar);
        BuscarCar.setVisible(true);
        
    }//GEN-LAST:event_item_buscarveiculoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        FecharVenda CloseVenda = new FecharVenda();
        jDesktopPane1.add(CloseVenda);
        CloseVenda.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        VisualizarPromos Visu = new VisualizarPromos();
        jDesktopPane1.add(Visu);
        Visu.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AC_PFUNCIONARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AC_PFUNCIONARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AC_PFUNCIONARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AC_PFUNCIONARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AC_PFUNCIONARIO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alt_cidade;
    private javax.swing.JTextField alt_cnh;
    private javax.swing.JTextField alt_cpf;
    private javax.swing.JTextField alt_email;
    private javax.swing.JTextField alt_estado;
    private javax.swing.JTextField alt_fone;
    private javax.swing.JTextField alt_nome;
    private javax.swing.JTextField alt_rg;
    private javax.swing.JMenuBar barra_menug;
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JLabel cnh;
    private javax.swing.JMenuItem item_alterarcliente;
    private javax.swing.JMenu item_buscarcliente;
    private javax.swing.JMenuItem item_buscarveiculo;
    private javax.swing.JMenuItem item_cadastrarcliente;
    private javax.swing.JMenuItem item_sair;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTClientes;
    private javax.swing.JLabel label_ac;
    private javax.swing.JLabel lbl_txt1;
    private javax.swing.JMenu menu_funcionario;
    private javax.swing.JMenu menu_status;
    private javax.swing.JPanel painel_fundo;
    private javax.swing.JTextField txt_busca;
    // End of variables declaration//GEN-END:variables
}
