/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AC_INICIO;
import AC_CONNECTBD.ConexaoAC;
import AC_DAO.AC_DAOVEICULOS;
import AC_MODEL.AC_MDCLIENTE;
import AC_MODEL.AC_MDVEICULOS;
import java.awt.Image;
import java.awt.Graphics;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LucasxTakeshi
 */
public class AC_PGERENTE extends javax.swing.JFrame {

    /**
     * Creates new form AC_PGERENTE
     */
    public AC_PGERENTE() {
        initComponents();
        Table();
        setTitle("Acesso exclusivo gerente - AutoCar");
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(640, 450);
    }

    public void Table(){
        
        DefaultTableModel model = (DefaultTableModel) jTVeiculos.getModel();
        model.setNumRows(0);
        AC_DAOVEICULOS vdao  = new AC_DAOVEICULOS();
        
        for (AC_MDVEICULOS v: vdao.Listar()){
            
            model.addRow(new Object[]{
            
                v.getIdveiculos(),
                v.getModelo(),
                v.getFabricante(),
                v.getCor(),
                v.getAno(),
                v.getPreco(),
                v.getChassi()
                
            });
            
        }
        
    }

    public void BuscarModel(String mode){
        
        DefaultTableModel model = (DefaultTableModel) jTVeiculos.getModel();
        model.setNumRows(0);
        AC_DAOVEICULOS vdao  = new AC_DAOVEICULOS();
        
        for (AC_MDVEICULOS v: vdao.BuscarModelo(mode)){
            
            model.addRow(new Object[]{
           
                v.getIdveiculos(),
                v.getModelo(),
                v.getFabricante(),
                v.getCor(),
                v.getAno(),
                v.getPreco(),
                v.getChassi()
                
            });
            
        }
        
    }
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_fundo = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTVeiculos = new javax.swing.JTable();
        lbl_txt1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        alt_chassi = new javax.swing.JTextField();
        alt_modelo = new javax.swing.JTextField();
        alt_fabricante = new javax.swing.JTextField();
        alt_cor = new javax.swing.JTextField();
        alt_ano = new javax.swing.JTextField();
        alt_preco = new javax.swing.JTextField();
        btn_alt = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        txt_busca = new javax.swing.JTextField();
        btn_atualizar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        label_ac = new javax.swing.JLabel();
        barra_menug = new javax.swing.JMenuBar();
        menu_gerente = new javax.swing.JMenu();
        item_alterar = new javax.swing.JMenuItem();
        item_comissoes = new javax.swing.JMenuItem();
        item_sair = new javax.swing.JMenuItem();
        menu_cadastrar = new javax.swing.JMenu();
        item_funcionario = new javax.swing.JMenuItem();
        item_promocao = new javax.swing.JMenuItem();
        item_veiculo = new javax.swing.JMenuItem();
        item_gerar = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        menu_sobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel_fundo.setBackground(new java.awt.Color(255, 255, 255));
        painel_fundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        painel_fundo.setForeground(new java.awt.Color(0, 0, 0));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jDesktopPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jDesktopPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jTVeiculos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MODELO", "FABRICANTE", "COR", "ANO", "PREÇO", "CHASSI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTVeiculosMouseClicked(evt);
            }
        });
        jTVeiculos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTVeiculosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTVeiculos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 30, 630, 160);

        lbl_txt1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_txt1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_txt1.setText("Todos os nossos veiculos");
        jPanel1.add(lbl_txt1);
        lbl_txt1.setBounds(230, 0, 170, 20);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 200, 630, 2);

        jLabel1.setText("Chassi :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(420, 250, 60, 20);

        jLabel2.setText("Modelo :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 210, 47, 20);

        jLabel3.setText("Fabricante :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 210, 70, 20);

        jLabel4.setText("Cor :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 210, 41, 20);

        jLabel5.setText("Ano :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 250, 41, 20);

        jLabel6.setText("Preço :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(240, 250, 50, 20);
        jPanel1.add(alt_chassi);
        alt_chassi.setBounds(480, 250, 120, 24);
        jPanel1.add(alt_modelo);
        alt_modelo.setBounds(90, 210, 120, 24);
        jPanel1.add(alt_fabricante);
        alt_fabricante.setBounds(290, 210, 120, 24);
        jPanel1.add(alt_cor);
        alt_cor.setBounds(480, 210, 120, 24);
        jPanel1.add(alt_ano);
        alt_ano.setBounds(90, 250, 120, 24);
        jPanel1.add(alt_preco);
        alt_preco.setBounds(290, 250, 120, 24);

        btn_alt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/page_edit.png"))); // NOI18N
        btn_alt.setText("ALTERAR DADOS");
        btn_alt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_altActionPerformed(evt);
            }
        });
        jPanel1.add(btn_alt);
        btn_alt.setBounds(20, 280, 160, 40);

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/zoom.png"))); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar);
        btn_buscar.setBounds(110, 0, 46, 20);

        txt_busca.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txt_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_busca);
        txt_busca.setBounds(0, 0, 110, 20);

        btn_atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/arrow_refresh.png"))); // NOI18N
        btn_atualizar.setText("ATUALIZAR");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_atualizar);
        btn_atualizar.setBounds(500, 0, 120, 20);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(0, 0, 630, 10);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(0, 20, 630, 10);

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(0, 50, 630, 360);

        label_ac.setFont(new java.awt.Font("Magneto", 1, 48)); // NOI18N
        label_ac.setForeground(new java.awt.Color(0, 0, 0));
        label_ac.setText(" AutoCar");
        jDesktopPane1.add(label_ac);
        label_ac.setBounds(180, 0, 260, 40);

        javax.swing.GroupLayout painel_fundoLayout = new javax.swing.GroupLayout(painel_fundo);
        painel_fundo.setLayout(painel_fundoLayout);
        painel_fundoLayout.setHorizontalGroup(
            painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        painel_fundoLayout.setVerticalGroup(
            painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        barra_menug.setBackground(new java.awt.Color(153, 153, 153));
        barra_menug.setForeground(new java.awt.Color(0, 0, 0));

        menu_gerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/user_gray.png"))); // NOI18N
        menu_gerente.setText("Gerente");

        item_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/car.png"))); // NOI18N
        item_alterar.setText("Alterar dados");
        item_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_alterarActionPerformed(evt);
            }
        });
        menu_gerente.add(item_alterar);

        item_comissoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/group_go.png"))); // NOI18N
        item_comissoes.setText("Comissões");
        item_comissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_comissoesActionPerformed(evt);
            }
        });
        menu_gerente.add(item_comissoes);

        item_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/door_out.png"))); // NOI18N
        item_sair.setText("Sair");
        item_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_sairActionPerformed(evt);
            }
        });
        menu_gerente.add(item_sair);

        barra_menug.add(menu_gerente);

        menu_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/user_add.png"))); // NOI18N
        menu_cadastrar.setText("Cadastrar");

        item_funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/user_add.png"))); // NOI18N
        item_funcionario.setText("Novo funcionário");
        item_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_funcionarioActionPerformed(evt);
            }
        });
        menu_cadastrar.add(item_funcionario);

        item_promocao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/add.png"))); // NOI18N
        item_promocao.setText("Nova Promoção");
        item_promocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_promocaoActionPerformed(evt);
            }
        });
        menu_cadastrar.add(item_promocao);

        item_veiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/car_add.png"))); // NOI18N
        item_veiculo.setText("Novo veículo");
        item_veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_veiculoActionPerformed(evt);
            }
        });
        menu_cadastrar.add(item_veiculo);

        barra_menug.add(menu_cadastrar);

        item_gerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/printer.png"))); // NOI18N
        item_gerar.setText("Relatórios");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/page_word.png"))); // NOI18N
        jMenuItem6.setText("Gerar relatórios");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        item_gerar.add(jMenuItem6);

        barra_menug.add(item_gerar);

        menu_sobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bullet_green.png"))); // NOI18N
        menu_sobre.setText("Status");
        menu_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sobreActionPerformed(evt);
            }
        });
        barra_menug.add(menu_sobre);

        setJMenuBar(barra_menug);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_sairActionPerformed
        new AC_ENTRADA().setVisible(true);
        dispose();
    }//GEN-LAST:event_item_sairActionPerformed

    private void item_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_funcionarioActionPerformed
        
        CadastrarFuncionario CadFunc = new CadastrarFuncionario();
        jDesktopPane1.add(CadFunc);
        CadFunc.setVisible(true);
        
    }//GEN-LAST:event_item_funcionarioActionPerformed

    private void item_veiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_veiculoActionPerformed
        
        CadastrarVeiculos CadVeic = new CadastrarVeiculos();
        jDesktopPane1.add(CadVeic);
        CadVeic.setVisible(true);
        
    }//GEN-LAST:event_item_veiculoActionPerformed

    private void btn_altActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_altActionPerformed
        
        if(jTVeiculos.getSelectedRow() != 1){
         
        Connection con = ConexaoAC.OpenConect();
        AC_MDVEICULOS v = new AC_MDVEICULOS();
        AC_DAOVEICULOS dao = new AC_DAOVEICULOS();
        AC_PGERENTE table = new AC_PGERENTE();

        v.setModelo(alt_modelo.getText());
        v.setFabricante(alt_fabricante.getText());
        v.setCor(alt_cor.getText());
        v.setAno(Integer.parseInt(alt_ano.getText()));
        v.setPreco(Double.parseDouble(alt_preco.getText()));
        v.setChassi(alt_chassi.getText());
        v.setIdveiculos((int)jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 0));
        
        dao.Alterar(v);
        
        alt_modelo.setText("");
        alt_fabricante.setText("");
        alt_cor.setText("");
        alt_ano.setText("");
        alt_preco.setText("");
        alt_chassi.setText("");
        
        
        Table();
        
        }else{
            
            JOptionPane.showMessageDialog(null, "Selecione uma veículo para fazer a alteração");
            
        }
                
    }//GEN-LAST:event_btn_altActionPerformed

    private void jTVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTVeiculosMouseClicked
        
        if(jTVeiculos.getSelectedRow() != 1){
            
            alt_modelo.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 1).toString());
            alt_fabricante.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 2).toString());
            alt_cor.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 3).toString());
            alt_ano.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 4).toString());
            alt_preco.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 5).toString());
            alt_chassi.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 6).toString());
            
        }
        
    }//GEN-LAST:event_jTVeiculosMouseClicked

    private void jTVeiculosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTVeiculosKeyReleased
        
        if(jTVeiculos.getSelectedRow() != 1){
            
            alt_modelo.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 1).toString());
            alt_fabricante.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 2).toString());
            alt_cor.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 3).toString());
            alt_ano.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 4).toString());
            alt_preco.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 5).toString());
            alt_chassi.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 6).toString());
            
        }
        
    }//GEN-LAST:event_jTVeiculosKeyReleased

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        
        BuscarModel(txt_busca.getText());
        
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void item_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_alterarActionPerformed
        
        JOptionPane.showMessageDialog(null, "Selecione um veículo na tabela.");
        
    }//GEN-LAST:event_item_alterarActionPerformed

    private void menu_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sobreActionPerformed
        
       
        
    }//GEN-LAST:event_menu_sobreActionPerformed

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        Table();
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void txt_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscaActionPerformed

    private void jDesktopPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDesktopPane1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jDesktopPane1AncestorAdded

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
        GerarRelatorios GerRel = new GerarRelatorios();
        jDesktopPane1.add(GerRel);
        GerRel.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void item_promocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_promocaoActionPerformed
        
        CadastrarPromo CadPro = new CadastrarPromo();
        jDesktopPane1.add(CadPro);
        CadPro.setVisible(true);
        
    }//GEN-LAST:event_item_promocaoActionPerformed

    private void item_comissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_comissoesActionPerformed
        
        Comissao Comi = new Comissao();
        jDesktopPane1.add(Comi);
        Comi.setVisible(true);
        
    }//GEN-LAST:event_item_comissoesActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AC_PGERENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AC_PGERENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AC_PGERENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AC_PGERENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AC_PGERENTE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alt_ano;
    private javax.swing.JTextField alt_chassi;
    private javax.swing.JTextField alt_cor;
    private javax.swing.JTextField alt_fabricante;
    private javax.swing.JTextField alt_modelo;
    private javax.swing.JTextField alt_preco;
    private javax.swing.JMenuBar barra_menug;
    private javax.swing.JButton btn_alt;
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JMenuItem item_alterar;
    private javax.swing.JMenuItem item_comissoes;
    private javax.swing.JMenuItem item_funcionario;
    private javax.swing.JMenu item_gerar;
    private javax.swing.JMenuItem item_promocao;
    private javax.swing.JMenuItem item_sair;
    private javax.swing.JMenuItem item_veiculo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTVeiculos;
    private javax.swing.JLabel label_ac;
    private javax.swing.JLabel lbl_txt1;
    private javax.swing.JMenu menu_cadastrar;
    private javax.swing.JMenu menu_gerente;
    private javax.swing.JMenu menu_sobre;
    private javax.swing.JPanel painel_fundo;
    private javax.swing.JTextField txt_busca;
    // End of variables declaration//GEN-END:variables

   
}
