/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AC_INICIO;

import AC_DAO.AC_DAOVEICULOS;
import AC_MODEL.AC_MDVEICULOS;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LucasxTakeshi
 */
public class BuscarVeiculos extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarVeiculos
     */
    public BuscarVeiculos() {
        initComponents();
        setLocation(0, 0);
        setSize(625, 390);
    }

    public void BuscarModel(String mode){
        
        DefaultTableModel model = (DefaultTableModel) jTVeiculos.getModel();
        model.setNumRows(0);
        AC_DAOVEICULOS vdao  = new AC_DAOVEICULOS();
        
        for (AC_MDVEICULOS v: vdao.BuscarModelo(mode)){
            
            model.addRow(new Object[]{
           
                v.getModelo(),
                v.getFabricante(),
                v.getCor(),
                v.getAno(),
                v.getPreco(),
                v.getChassi()
                
            });
            
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_fundo = new javax.swing.JPanel();
        txt_busca = new javax.swing.JTextField();
        btn_busca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTVeiculos = new javax.swing.JTable();

        setClosable(true);
        setTitle("Buscar veículos");

        painel_fundo.setBackground(new java.awt.Color(255, 255, 255));
        painel_fundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        painel_fundo.setForeground(new java.awt.Color(0, 0, 0));
        painel_fundo.setLayout(null);
        painel_fundo.add(txt_busca);
        txt_busca.setBounds(70, 40, 355, 24);

        btn_busca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/zoom.png"))); // NOI18N
        btn_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscaActionPerformed(evt);
            }
        });
        painel_fundo.add(btn_busca);
        btn_busca.setBounds(460, 40, 70, 24);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Informe o nome do veículo:");
        painel_fundo.add(jLabel1);
        jLabel1.setBounds(70, 10, 187, 26);

        jTVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Fabricante", "Cor", "Ano", "Preço", "Chassi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTVeiculos);

        painel_fundo.add(jScrollPane2);
        jScrollPane2.setBounds(40, 90, 540, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel_fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscaActionPerformed
        
        BuscarModel(txt_busca.getText());
        
    }//GEN-LAST:event_btn_buscaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_busca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTVeiculos;
    private javax.swing.JPanel painel_fundo;
    private javax.swing.JTextField txt_busca;
    // End of variables declaration//GEN-END:variables
}
