/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AC_INICIO;

import AC_CONNECTBD.ConexaoAC;
import AC_DAO.AC_DAOCLIENTE;
import AC_MODEL.AC_MDCLIENTE;
import java.sql.Connection;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author LucasxTakeshi
 */
public class CadastrarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarCliente
     */
    public CadastrarCliente() {
        initComponents();
        initComponents();
        FormatCamp();
        setLocation(110, 0);
    }

        private void FormatCamp(){
        
        try {
            
            MaskFormatter cpf = new MaskFormatter("###.###.###-##");
            cpf.install(txt_cpf);
            
            MaskFormatter fone = new MaskFormatter("(##)#####-####");
            fone.install(txt_fone);
            
            MaskFormatter rg = new MaskFormatter("##.###.###");
            rg.install(txt_rg);
            
        } catch (ParseException ex) {
        
            JOptionPane.showMessageDialog(null, "Erro na formatação do campo", "Erro", JOptionPane.ERROR_MESSAGE);
        
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_nome = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_cpf = new javax.swing.JLabel();
        lbl_fone = new javax.swing.JLabel();
        lbl_rg = new javax.swing.JLabel();
        lbl_end = new javax.swing.JLabel();
        lbl_login = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_cpf = new javax.swing.JFormattedTextField();
        txt_fone = new javax.swing.JFormattedTextField();
        txt_rg = new javax.swing.JFormattedTextField();
        txt_cid = new javax.swing.JTextField();
        txt_cnh = new javax.swing.JTextField();
        lbl_senha = new javax.swing.JLabel();
        btn_cadfunc = new javax.swing.JButton();
        txt_est = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastro de cliente - AutoCar");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.setLayout(null);

        lbl_nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_nome.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nome.setText("Nome :");
        jPanel1.add(lbl_nome);
        lbl_nome.setBounds(20, 10, 50, 30);

        lbl_email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(0, 0, 0));
        lbl_email.setText("E-mail :");
        jPanel1.add(lbl_email);
        lbl_email.setBounds(20, 50, 50, 30);

        lbl_cpf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_cpf.setForeground(new java.awt.Color(0, 0, 0));
        lbl_cpf.setText("CPF :");
        jPanel1.add(lbl_cpf);
        lbl_cpf.setBounds(20, 90, 40, 30);

        lbl_fone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_fone.setForeground(new java.awt.Color(0, 0, 0));
        lbl_fone.setText("Fone  :");
        jPanel1.add(lbl_fone);
        lbl_fone.setBounds(190, 90, 50, 30);

        lbl_rg.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_rg.setForeground(new java.awt.Color(0, 0, 0));
        lbl_rg.setText("RG :");
        jPanel1.add(lbl_rg);
        lbl_rg.setBounds(20, 130, 30, 30);

        lbl_end.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_end.setForeground(new java.awt.Color(0, 0, 0));
        lbl_end.setText("Cidade :");
        jPanel1.add(lbl_end);
        lbl_end.setBounds(20, 170, 60, 30);

        lbl_login.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_login.setForeground(new java.awt.Color(0, 0, 0));
        lbl_login.setText("Estado :");
        jPanel1.add(lbl_login);
        lbl_login.setBounds(20, 210, 60, 30);

        txt_nome.setBackground(new java.awt.Color(255, 255, 255));
        txt_nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_nome.setForeground(new java.awt.Color(0, 0, 0));
        txt_nome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(txt_nome);
        txt_nome.setBounds(70, 10, 300, 30);

        txt_email.setBackground(new java.awt.Color(255, 255, 255));
        txt_email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(0, 0, 0));
        txt_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(txt_email);
        txt_email.setBounds(70, 50, 300, 30);

        txt_cpf.setBackground(new java.awt.Color(255, 255, 255));
        txt_cpf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_cpf.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txt_cpf);
        txt_cpf.setBounds(70, 90, 110, 30);

        txt_fone.setBackground(new java.awt.Color(255, 255, 255));
        txt_fone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_fone.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txt_fone);
        txt_fone.setBounds(240, 90, 130, 30);

        txt_rg.setBackground(new java.awt.Color(255, 255, 255));
        txt_rg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_rg.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txt_rg);
        txt_rg.setBounds(70, 130, 300, 30);

        txt_cid.setBackground(new java.awt.Color(255, 255, 255));
        txt_cid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_cid.setForeground(new java.awt.Color(0, 0, 0));
        txt_cid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cidActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cid);
        txt_cid.setBounds(80, 170, 290, 30);

        txt_cnh.setBackground(new java.awt.Color(255, 255, 255));
        txt_cnh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_cnh.setForeground(new java.awt.Color(0, 0, 0));
        txt_cnh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_cnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cnhActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cnh);
        txt_cnh.setBounds(80, 250, 290, 30);

        lbl_senha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_senha.setForeground(new java.awt.Color(0, 0, 0));
        lbl_senha.setText("CNH :");
        jPanel1.add(lbl_senha);
        lbl_senha.setBounds(20, 250, 50, 30);

        btn_cadfunc.setBackground(new java.awt.Color(51, 255, 51));
        btn_cadfunc.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btn_cadfunc.setForeground(new java.awt.Color(0, 0, 0));
        btn_cadfunc.setText("CADASTRAR");
        btn_cadfunc.setBorder(new javax.swing.border.MatteBorder(null));
        btn_cadfunc.setOpaque(false);
        btn_cadfunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadfuncActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cadfunc);
        btn_cadfunc.setBounds(130, 290, 140, 40);

        txt_est.setBackground(new java.awt.Color(255, 255, 255));
        txt_est.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_est.setForeground(new java.awt.Color(0, 0, 0));
        txt_est.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(txt_est);
        txt_est.setBounds(80, 210, 290, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cidActionPerformed

    private void btn_cadfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadfuncActionPerformed

        Connection con = ConexaoAC.OpenConect();
        AC_MDCLIENTE a = new AC_MDCLIENTE();
        AC_DAOCLIENTE dao = new AC_DAOCLIENTE();

        a.setNome(txt_nome.getText());
        a.setEmail(txt_email.getText());
        a.setCpf(txt_cpf.getText());
        a.setTelefone(txt_fone.getText());
        a.setRg(txt_rg.getText());
        a.setCidade(txt_cid.getText());
        a.setEstado(txt_cnh.getText());
        a.setCnh(txt_cnh.getText());

        dao.SaveC(a);
        dispose();
    }//GEN-LAST:event_btn_cadfuncActionPerformed

    private void txt_cnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cnhActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadfunc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_end;
    private javax.swing.JLabel lbl_fone;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_rg;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JTextField txt_cid;
    private javax.swing.JTextField txt_cnh;
    private javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_est;
    private javax.swing.JFormattedTextField txt_fone;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JFormattedTextField txt_rg;
    // End of variables declaration//GEN-END:variables
}
