/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AC_INICIO;

import AC_CONNECTBD.ConexaoAC;
import AC_DAO.AC_DAOVEICULOS;
import AC_MODEL.AC_MDVEICULOS;
import java.sql.Connection;

/**
 *
 * @author LucasxTakeshi
 */
public class CadastrarVeiculos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarVeiculos
     */
    public CadastrarVeiculos() {
        initComponents();
        setLocation(110, 30);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_nome = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_cpf = new javax.swing.JLabel();
        lbl_fone = new javax.swing.JLabel();
        lbl_rg = new javax.swing.JLabel();
        lbl_end = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        txt_fab = new javax.swing.JTextField();
        txt_cor = new javax.swing.JFormattedTextField();
        txt_ano = new javax.swing.JFormattedTextField();
        txt_preco = new javax.swing.JFormattedTextField();
        txt_chassi = new javax.swing.JTextField();
        btn_cadfunc = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastrar um novo veículo");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.setLayout(null);

        lbl_nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_nome.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nome.setText("Modelo : ");
        jPanel1.add(lbl_nome);
        lbl_nome.setBounds(20, 10, 60, 30);

        lbl_email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(0, 0, 0));
        lbl_email.setText("Fabricante :");
        jPanel1.add(lbl_email);
        lbl_email.setBounds(20, 50, 80, 30);

        lbl_cpf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_cpf.setForeground(new java.awt.Color(0, 0, 0));
        lbl_cpf.setText("Cor :");
        jPanel1.add(lbl_cpf);
        lbl_cpf.setBounds(20, 90, 40, 30);

        lbl_fone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_fone.setForeground(new java.awt.Color(0, 0, 0));
        lbl_fone.setText("Ano :");
        jPanel1.add(lbl_fone);
        lbl_fone.setBounds(220, 90, 40, 30);

        lbl_rg.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_rg.setForeground(new java.awt.Color(0, 0, 0));
        lbl_rg.setText("Preço :");
        jPanel1.add(lbl_rg);
        lbl_rg.setBounds(20, 130, 50, 30);

        lbl_end.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_end.setForeground(new java.awt.Color(0, 0, 0));
        lbl_end.setText("Chassi :");
        jPanel1.add(lbl_end);
        lbl_end.setBounds(20, 170, 70, 30);

        txt_modelo.setBackground(new java.awt.Color(255, 255, 255));
        txt_modelo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_modelo.setForeground(new java.awt.Color(0, 0, 0));
        txt_modelo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(txt_modelo);
        txt_modelo.setBounds(100, 10, 280, 30);

        txt_fab.setBackground(new java.awt.Color(255, 255, 255));
        txt_fab.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_fab.setForeground(new java.awt.Color(0, 0, 0));
        txt_fab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(txt_fab);
        txt_fab.setBounds(100, 50, 280, 30);

        txt_cor.setBackground(new java.awt.Color(255, 255, 255));
        txt_cor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_cor.setForeground(new java.awt.Color(0, 0, 0));
        txt_cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_corActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cor);
        txt_cor.setBounds(100, 90, 110, 30);

        txt_ano.setBackground(new java.awt.Color(255, 255, 255));
        txt_ano.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_ano.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txt_ano);
        txt_ano.setBounds(260, 90, 120, 30);

        txt_preco.setBackground(new java.awt.Color(255, 255, 255));
        txt_preco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_preco.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txt_preco);
        txt_preco.setBounds(100, 130, 280, 30);

        txt_chassi.setBackground(new java.awt.Color(255, 255, 255));
        txt_chassi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_chassi.setForeground(new java.awt.Color(0, 0, 0));
        txt_chassi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_chassi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_chassiActionPerformed(evt);
            }
        });
        jPanel1.add(txt_chassi);
        txt_chassi.setBounds(100, 170, 280, 30);

        btn_cadfunc.setBackground(new java.awt.Color(51, 255, 51));
        btn_cadfunc.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btn_cadfunc.setForeground(new java.awt.Color(0, 0, 0));
        btn_cadfunc.setText("CADASTRAR");
        btn_cadfunc.setBorder(new javax.swing.border.MatteBorder(null));
        btn_cadfunc.setOpaque(false);
        btn_cadfunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadfuncActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cadfunc);
        btn_cadfunc.setBounds(130, 230, 140, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_chassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_chassiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_chassiActionPerformed

    private void btn_cadfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadfuncActionPerformed

        Connection con = ConexaoAC.OpenConect();
        AC_MDVEICULOS v = new AC_MDVEICULOS();
        AC_DAOVEICULOS dao = new AC_DAOVEICULOS();
        AC_PGERENTE table = new AC_PGERENTE();

        v.setModelo(txt_modelo.getText());
        v.setFabricante(txt_fab.getText());
        v.setCor(txt_cor.getText());
        v.setAno(Integer.parseInt(txt_ano.getText()));
        v.setPreco(Double.parseDouble(txt_preco.getText()));
        v.setChassi(txt_chassi.getText());
        
        dao.SaveCar(v);
        dispose();
        
    }//GEN-LAST:event_btn_cadfuncActionPerformed

    private void txt_corActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_corActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_corActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadfunc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_end;
    private javax.swing.JLabel lbl_fone;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_rg;
    private javax.swing.JFormattedTextField txt_ano;
    private javax.swing.JTextField txt_chassi;
    private javax.swing.JFormattedTextField txt_cor;
    private javax.swing.JTextField txt_fab;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JFormattedTextField txt_preco;
    // End of variables declaration//GEN-END:variables
}
