/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AC_INICIO;

import AC_CONNECTBD.ConexaoAC;
import AC_DAO.AC_DAOPROMOCAO;
import AC_DAO.AC_DAOVEICULOS;
import AC_MODEL.AC_MDPROMOCAO;
import AC_MODEL.AC_MDVEICULOS;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LucasxTakeshi
 */
public class CadastrarPromo extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarPromo
     */
    public CadastrarPromo() {
        initComponents();
        Table();
    }

            public void Table(){
        
        DefaultTableModel model = (DefaultTableModel) jTVeiculos.getModel();
        model.setNumRows(0);
        AC_DAOVEICULOS vdao  = new AC_DAOVEICULOS();
        
        for (AC_MDVEICULOS v: vdao.Listar()){
            
            model.addRow(new Object[]{
            
                
                v.getModelo(),
                v.getFabricante(),
                v.getPreco(),
                v.getChassi()
                
            });
            
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_fundo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTVeiculos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_fabri = new javax.swing.JTextField();
        txt_preco = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_promo = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_chassi = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Adicionar uma promoção");

        painel_fundo.setBackground(new java.awt.Color(255, 255, 255));
        painel_fundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        painel_fundo.setForeground(new java.awt.Color(0, 0, 0));
        painel_fundo.setLayout(null);

        jTVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Fabricante", "Preço", "Chassi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTVeiculosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTVeiculos);

        painel_fundo.add(jScrollPane2);
        jScrollPane2.setBounds(40, 150, 540, 180);

        jLabel3.setText("Modelo :");
        painel_fundo.add(jLabel3);
        jLabel3.setBounds(70, 20, 50, 16);

        jLabel4.setText("Fabricante :");
        painel_fundo.add(jLabel4);
        jLabel4.setBounds(300, 20, 70, 16);

        jLabel5.setText("Preço :");
        painel_fundo.add(jLabel5);
        jLabel5.setBounds(80, 60, 40, 16);

        jLabel7.setText("Promoção :");
        painel_fundo.add(jLabel7);
        jLabel7.setBounds(50, 100, 70, 16);

        jLabel9.setText("Chassi :");
        painel_fundo.add(jLabel9);
        jLabel9.setBounds(320, 60, 50, 16);
        painel_fundo.add(txt_fabri);
        txt_fabri.setBounds(380, 10, 160, 30);
        painel_fundo.add(txt_preco);
        txt_preco.setBounds(130, 50, 160, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/accept.png"))); // NOI18N
        jButton1.setText("CONCLUIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        painel_fundo.add(jButton1);
        jButton1.setBounds(380, 90, 160, 32);
        painel_fundo.add(txt_promo);
        txt_promo.setBounds(130, 90, 160, 30);

        txt_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_modeloActionPerformed(evt);
            }
        });
        painel_fundo.add(txt_modelo);
        txt_modelo.setBounds(130, 10, 160, 30);
        painel_fundo.add(txt_chassi);
        txt_chassi.setBounds(380, 50, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTVeiculosMouseClicked

        if(jTVeiculos.getSelectedRow() != 1){

            txt_modelo.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 0).toString());
            txt_fabri.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 1).toString());
            txt_preco.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 2).toString());
            txt_chassi.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 3).toString());

        }

    }//GEN-LAST:event_jTVeiculosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Connection con = ConexaoAC.OpenConect();
        AC_MDPROMOCAO p = new AC_MDPROMOCAO();
        AC_DAOPROMOCAO dao = new AC_DAOPROMOCAO();

        p.setModelo(txt_modelo.getText());
        p.setFabricante(txt_fabri.getText());
        p.setPreco(Float.parseFloat(txt_preco.getText()));
        p.setChassi(txt_chassi.getText());
        p.setPromocao(txt_promo.getText());
        
        dao.SavePromo(p);
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_modeloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTVeiculos;
    private javax.swing.JPanel painel_fundo;
    private javax.swing.JTextField txt_chassi;
    private javax.swing.JTextField txt_fabri;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JTextField txt_promo;
    // End of variables declaration//GEN-END:variables
}
