/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AC_INICIO;

import AC_CONNECTBD.ConexaoAC;
import AC_DAO.AC_DAOCOMISSAO;
import AC_DAO.AC_DAOVENDAS;
import AC_MODEL.AC_MDCOMISSAO;
import AC_MODEL.AC_MDVENDAS;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LucasxTakeshi
 */
public class Comissao extends javax.swing.JInternalFrame {

    /**
     * Creates new form Comissao
     */
    public Comissao() {
        initComponents();
        Table();
        setLocation(0, 0);
        setSize(625, 380);
    }

    public void Table(){
        
        DefaultTableModel model = (DefaultTableModel) jTFuncionarios.getModel();
        model.setNumRows(0);
        AC_DAOVENDAS vdao  = new AC_DAOVENDAS();
        
        for (AC_MDVENDAS v: vdao.Listar()){
            
            model.addRow(new Object[]{
            
                v.getNomefunc(),
                v.getChassi(),
                v.getDesconto(),
                v.getValortotal()
                
            });
            
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_fundo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTFuncionarios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_desconto = new javax.swing.JTextField();
        txt_chassi = new javax.swing.JTextField();
        txt_func = new javax.swing.JTextField();
        txt_valor = new javax.swing.JTextField();
        txt_comi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gerar comissões");

        painel_fundo.setBackground(new java.awt.Color(255, 255, 255));
        painel_fundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        painel_fundo.setForeground(new java.awt.Color(0, 0, 0));
        painel_fundo.setLayout(null);

        jTFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Funcionário", "Chassi", "Desconto", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTFuncionarios);

        painel_fundo.add(jScrollPane2);
        jScrollPane2.setBounds(40, 150, 540, 180);

        jLabel3.setText("Funcionário :");
        painel_fundo.add(jLabel3);
        jLabel3.setBounds(70, 20, 80, 16);

        jLabel4.setText("Chassi :");
        painel_fundo.add(jLabel4);
        jLabel4.setBounds(320, 20, 45, 16);

        jLabel5.setText("Desconto :");
        painel_fundo.add(jLabel5);
        jLabel5.setBounds(80, 60, 60, 16);

        jLabel6.setText("Valor :");
        painel_fundo.add(jLabel6);
        jLabel6.setBounds(330, 60, 40, 16);

        jLabel7.setText("Comissão :");
        painel_fundo.add(jLabel7);
        jLabel7.setBounds(80, 100, 70, 16);
        painel_fundo.add(txt_desconto);
        txt_desconto.setBounds(160, 50, 130, 30);
        painel_fundo.add(txt_chassi);
        txt_chassi.setBounds(390, 10, 130, 30);
        painel_fundo.add(txt_func);
        txt_func.setBounds(160, 10, 130, 30);
        painel_fundo.add(txt_valor);
        txt_valor.setBounds(390, 50, 130, 30);
        painel_fundo.add(txt_comi);
        txt_comi.setBounds(160, 90, 130, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/accept.png"))); // NOI18N
        jButton1.setText("CONCLUIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        painel_fundo.add(jButton1);
        jButton1.setBounds(390, 90, 130, 32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuncionariosMouseClicked

        if(jTFuncionarios.getSelectedRow() != 1){

            txt_func.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 0).toString());
            txt_chassi.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 1).toString());
            txt_desconto.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 2).toString());
            txt_valor.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 3).toString());

        }

    }//GEN-LAST:event_jTFuncionariosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Connection con = ConexaoAC.OpenConect();
        AC_MDCOMISSAO c = new AC_MDCOMISSAO();
        AC_DAOCOMISSAO dao = new AC_DAOCOMISSAO();

        c.setFuncionario(txt_func.getText());
        c.setChassi(txt_chassi.getText());
        c.setDesconto(txt_desconto.getText());
        c.setValor(Float.parseFloat(txt_valor.getText()));
        c.setComissao(Float.parseFloat(txt_comi.getText()));
       
        dao.SaveCom(c);
        dispose();

        if(jTFuncionarios.getSelectedRow() != -1){

            AC_MDCOMISSAO d = new AC_MDCOMISSAO();
            AC_DAOCOMISSAO ddao = new AC_DAOCOMISSAO();
            d.setFuncionario((String) jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 0));
            ddao.delete(d);
            Table();

        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTFuncionarios;
    private javax.swing.JPanel painel_fundo;
    private javax.swing.JTextField txt_chassi;
    private javax.swing.JTextField txt_comi;
    private javax.swing.JTextField txt_desconto;
    private javax.swing.JTextField txt_func;
    private javax.swing.JTextField txt_valor;
    // End of variables declaration//GEN-END:variables
}
