/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AC_INICIO;

import AC_CONNECTBD.ConexaoAC;
import AC_DAO.AC_DAOVEICULOS;
import AC_DAO.AC_DAOVENDAS;
import AC_MODEL.AC_MDVEICULOS;
import AC_MODEL.AC_MDVENDAS;
import java.sql.Connection;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author LucasxTakeshi
 */
public class FecharVenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form FecharVenda
     */
    public FecharVenda() {
        initComponents();
        Table();
        setLocation(0, 0);
        setSize(625, 390);
    }

        public void Table(){
        
        DefaultTableModel model = (DefaultTableModel) jTVeiculos.getModel();
        model.setNumRows(0);
        AC_DAOVEICULOS vdao  = new AC_DAOVEICULOS();
        
        for (AC_MDVEICULOS v: vdao.Listar()){
            
            model.addRow(new Object[]{
            
                
                v.getModelo(),
                v.getFabricante(),
                v.getCor(),
                v.getAno(),
                v.getPreco(),
                v.getChassi()
                
            });
            
        }
        
    }
        

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_fundo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTVeiculos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_data = new javax.swing.JTextField();
        txt_servico = new javax.swing.JTextField();
        txt_nomec = new javax.swing.JTextField();
        txt_nomef = new javax.swing.JTextField();
        txt_formapag = new javax.swing.JTextField();
        txt_desconto = new javax.swing.JTextField();
        txt_valor = new javax.swing.JTextField();
        txt_chassi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Fechar uma venda");

        painel_fundo.setBackground(new java.awt.Color(255, 255, 255));
        painel_fundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        painel_fundo.setForeground(new java.awt.Color(0, 0, 0));
        painel_fundo.setLayout(null);

        jTVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Fabricante", "Cor", "Ano", "Preço", "Chassi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTVeiculosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTVeiculos);

        painel_fundo.add(jScrollPane2);
        jScrollPane2.setBounds(40, 150, 540, 180);

        jLabel2.setText("Data :");
        painel_fundo.add(jLabel2);
        jLabel2.setBounds(150, 100, 40, 16);

        jLabel3.setText("Informe seu nome :");
        painel_fundo.add(jLabel3);
        jLabel3.setBounds(20, 20, 110, 16);

        jLabel4.setText("Nome do cliente :");
        painel_fundo.add(jLabel4);
        jLabel4.setBounds(240, 20, 100, 16);

        jLabel5.setText("Serviços ADD  :");
        painel_fundo.add(jLabel5);
        jLabel5.setBounds(20, 60, 86, 16);

        jLabel6.setText("Desconto :");
        painel_fundo.add(jLabel6);
        jLabel6.setBounds(450, 20, 60, 16);

        jLabel7.setText("Valor total :");
        painel_fundo.add(jLabel7);
        jLabel7.setBounds(230, 60, 70, 16);

        jLabel8.setText("Forma de pagamento :");
        painel_fundo.add(jLabel8);
        jLabel8.setBounds(380, 60, 130, 16);

        jLabel9.setText("Chassi :");
        painel_fundo.add(jLabel9);
        jLabel9.setBounds(20, 100, 50, 16);
        painel_fundo.add(txt_data);
        txt_data.setBounds(190, 90, 70, 30);
        painel_fundo.add(txt_servico);
        txt_servico.setBounds(110, 50, 110, 30);
        painel_fundo.add(txt_nomec);
        txt_nomec.setBounds(340, 10, 100, 30);
        painel_fundo.add(txt_nomef);
        txt_nomef.setBounds(130, 10, 100, 30);
        painel_fundo.add(txt_formapag);
        txt_formapag.setBounds(510, 50, 90, 30);
        painel_fundo.add(txt_desconto);
        txt_desconto.setBounds(510, 10, 90, 30);
        painel_fundo.add(txt_valor);
        txt_valor.setBounds(300, 50, 70, 30);
        painel_fundo.add(txt_chassi);
        txt_chassi.setBounds(70, 90, 70, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/accept.png"))); // NOI18N
        jButton1.setText("CONCLUIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        painel_fundo.add(jButton1);
        jButton1.setBounds(300, 90, 120, 32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Connection con = ConexaoAC.OpenConect();
        AC_MDVENDAS f = new AC_MDVENDAS();
        AC_DAOVENDAS dao = new AC_DAOVENDAS();
        

        f.setNomefunc(txt_nomef.getText());
        f.setNomeclie(txt_nomec.getText());
        f.setDesconto(txt_desconto.getText());
        f.setServicosadd(txt_servico.getText());
        f.setValortotal(Double.parseDouble(txt_valor.getText()));
        f.setFormapag(txt_formapag.getText());
        f.setChassi(txt_chassi.getText());
        f.setData(txt_data.getText());
        
        dao.SaveV(f);
        dispose();
         
         if(jTVeiculos.getSelectedRow() != -1){
            
         AC_MDVEICULOS d = new AC_MDVEICULOS();
         AC_DAOVEICULOS ddao = new AC_DAOVEICULOS();
         d.setModelo((String) jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 0));
         ddao.delete(d);
         Table();
      
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTVeiculosMouseClicked
        
        if(jTVeiculos.getSelectedRow() != 1){

            txt_chassi.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 5).toString());
            
        }
        
    }//GEN-LAST:event_jTVeiculosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTVeiculos;
    private javax.swing.JPanel painel_fundo;
    private javax.swing.JTextField txt_chassi;
    private javax.swing.JTextField txt_data;
    private javax.swing.JTextField txt_desconto;
    private javax.swing.JTextField txt_formapag;
    private javax.swing.JTextField txt_nomec;
    private javax.swing.JTextField txt_nomef;
    private javax.swing.JTextField txt_servico;
    private javax.swing.JTextField txt_valor;
    // End of variables declaration//GEN-END:variables
}
