/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AC_INICIO;

import AC_DAO.AC_DAOVENDAS;
import AC_MODEL.AC_MDVENDAS;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LucasxTakeshi
 */
public class GerarRelatorios extends javax.swing.JInternalFrame {

    /**
     * Creates new form GerarRelatorios
     */
    public GerarRelatorios() {
        initComponents();
        setLocation(0, 0);
        setSize(625, 380);
        Table();
    }

        public void Table(){
        
        DefaultTableModel model = (DefaultTableModel) jTRelatorio.getModel();
        model.setNumRows(0);
            AC_DAOVENDAS vdao  = new AC_DAOVENDAS();
        
        for (AC_MDVENDAS v: vdao.Listar()){
            
            model.addRow(new Object[]{
            
                v.getNomefunc(),
                v.getNomeclie(),
                v.getChassi(),
                v.getDesconto(),
                v.getValortotal()
                
            });
            
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_fundo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTRelatorio = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Relatórios de vendas");

        painel_fundo.setBackground(new java.awt.Color(255, 255, 255));
        painel_fundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        painel_fundo.setForeground(new java.awt.Color(0, 0, 0));
        painel_fundo.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Relatórios de vendas realizadas");
        painel_fundo.add(jLabel1);
        jLabel1.setBounds(150, 10, 300, 40);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        painel_fundo.add(jSeparator1);
        jSeparator1.setBounds(180, 40, 210, 2);

        jTRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Funcionário", "Cliente", "Chassi", "Desconto", "Valor total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTRelatorio);

        painel_fundo.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 570, 230);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/delete.png"))); // NOI18N
        jButton1.setText("Excluir relatórios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        painel_fundo.add(jButton1);
        jButton1.setBounds(220, 300, 160, 32);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/arrow_refresh.png"))); // NOI18N
        jButton2.setText("Atualizar relatórios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        painel_fundo.add(jButton2);
        jButton2.setBounds(20, 300, 158, 32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Table();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jTRelatorio.getSelectedRow() != -1){
            
         AC_MDVENDAS p = new AC_MDVENDAS();
         AC_DAOVENDAS dao = new AC_DAOVENDAS();
         p.setNomefunc((String) jTRelatorio.getValueAt(jTRelatorio.getSelectedRow(), 0));
         dao.delete(p);
         Table();
      
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTRelatorio;
    private javax.swing.JPanel painel_fundo;
    // End of variables declaration//GEN-END:variables
}
