/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AC_INICIO;

import AC_DAO.AC_DAOPROMOCAO;
import AC_MODEL.AC_MDPROMOCAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LucasxTakeshi
 */
public class VisualizarPromos extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisualizarPromos
     */
    public VisualizarPromos() {
        initComponents();
        setLocation(0, 0);
        setSize(625, 390);
        Table();
    }

    public void Table(){
        
        DefaultTableModel model = (DefaultTableModel) jTRelatorio.getModel();
        model.setNumRows(0);
        AC_DAOPROMOCAO pdao  = new AC_DAOPROMOCAO();
        
        for (AC_MDPROMOCAO p: pdao.Listar()){
            
            model.addRow(new Object[]{
            
                p.getModelo(),
                p.getFabricante(),
                p.getPreco(),
                p.getChassi(),
                p.getPromocao()
                
            });
            
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_fundo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTRelatorio = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Todas as promoções");

        painel_fundo.setBackground(new java.awt.Color(255, 255, 255));
        painel_fundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        painel_fundo.setForeground(new java.awt.Color(0, 0, 0));
        painel_fundo.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Promoções cadastradas");
        painel_fundo.add(jLabel1);
        jLabel1.setBounds(180, 10, 210, 40);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        painel_fundo.add(jSeparator1);
        jSeparator1.setBounds(180, 40, 210, 2);

        jTRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Fabricante", "Preco", "Chassi", "Promoção"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTRelatorio);
        if (jTRelatorio.getColumnModel().getColumnCount() > 0) {
            jTRelatorio.getColumnModel().getColumn(4).setResizable(false);
        }

        painel_fundo.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 570, 230);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/arrow_refresh.png"))); // NOI18N
        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        painel_fundo.add(jButton2);
        jButton2.setBounds(20, 300, 130, 32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel_fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Table();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTRelatorio;
    private javax.swing.JPanel painel_fundo;
    // End of variables declaration//GEN-END:variables
}
